### ISSUE TITLE
Q1 - Print All Unique Permutations

### ISSUE THREAD

**Issue by dreamerHarshit** [dreamerHarshit/Coding_Questions#2]
```
I/P - [1,1,2]

o/p -

[1,1,2]
[1,2,1]
[2,1,1] 
```

**Comment by shauniop** [comment]
from itertools import permutations 
  
# Get all permutations of list a = [1, 1, 2] 
a = [1, 1, 2]
perm = permutations(a)
  
# Print the obtained permutations 
for i in list(set(perm)):
    print(i)

**Comment by dreamerHarshit** [comment]
we have to do it without using library function.

**Comment by dreamerHarshit** [comment]
#
